server.port: 9090

# DB connection
spring.data.mongodb:
  database: payme
  host: localhost
  port: 27017
  
# Email settings
netcore.mail:
  host: smtp.falconide.com
  username: citruspay
  password: Ci7ru$p@y
  debug: false
  smtpAuth: true
  smtpStarttlsEnable: false
  smtpPort: 25
  
payme:
  baseUrl: http://localhost:9090
  contact: contact@spayme.com
  env: test