spring:
  datasource:
    driverClassName: org.postgresql.Driver
    initialSize: 5
    maxActive: 10
    maxIdle: 5
    minIdle: 2
    password: C@rpe_d!em
    removeAbandoned: true
    url: jdbc:postgresql://localhost:5432/paycr
    username: postgres
  flyway:
    baselineOnMigrate: true
  freemarker:
    suffix: .html
  jpa:
    hibernate:
      ddl-auto: update

company:
  merchant:
    id: 1
  url:
    web: http://localhost:4200
    oauth: http://localhost:8080
  contact:
    name: Paycr Noreply
    email: noreply@paycr.in
    password: C@rpe_d!em