server:
  port: 7070

admin:
  location:
    banner: /opt/paycr/static/admin/

bulk:
  location:
    asset: /opt/paycr/static/bulk/asset/
    consumer: /opt/paycr/static/bulk/consumer/
    inventory: /opt/paycr/static/bulk/inventory/
    invoice: /opt/paycr/static/bulk/invoice/
    supplier: /opt/paycr/static/bulk/supplier/

expense:
  location:
    attachment: /opt/paycr/static/expattach/
    pdf: /opt/paycr/static/expense/

invoice:
  location:
    attachment: /opt/paycr/static/invattach/
    pdf: /opt/paycr/static/invoice/

merchant:
  location:
    banner: /opt/paycr/static/merchant/
    gst: /opt/paycr/static/gst/

payment:
  location:
    pdf: /opt/paycr/static/payment/

report:
  location:
    pdf: /opt/paycr/static/report/

subscription:
  location:
    pdf: /opt/paycr/static/subscription/

wkhtmltopdf:
  location: /usr/bin/

cron:
  invoice:
    expire: 0 0 1 * * ?
    recurring: 0 0 4 * * ?
    remind: 0 0 6 * * ?
  report:
    scheduler: 0 0 0 * * ?
    reinit: 0 0 16 * * ?