package com.paycr.common.type;

public enum Role {

	ROLE_PAYCR, ROLE_PAYCR_SUPERVISOR, ROLE_PAYCR_FINANCE, ROLE_PAYCR_OPS, ROLE_PAYCR_ADVISOR, 
	ROLE_MERCHANT, ROLE_MERCHANT_FINANCE, ROLE_MERCHANT_OPS;

}
